language: go
sudo: false
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - cd mikrocount && dep ensure
before_script:
  - go vet ./...
script:
  - echo "All done for now. More to come..."
